"""v1 schema: six tables, four views.

Revision ID: 0001_v1_schema
Revises:
Create Date: 2026-10-01

Written by hand rather than autogenerated, because the views are not in the model
metadata and `gen_random_uuid()` is a database default the ORM does not express.
The column set matches `Specs - Database schema` exactly.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001_v1_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TRACKING = "('reps_weight','reps_only','duration','completion','distance_duration')"
WEIGHT_BASIS = "('total','per_hand')"
SET_STATUS = "('done','missed','skipped')"

TAIL = [
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("extra", postgresql.JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
]


def upgrade() -> None:
    # ---------------------------------------------------------------- exercise
    op.create_table(
        "exercise",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("name", sa.Text, nullable=False, unique=True),
        sa.Column("tracking", sa.Text, nullable=False, server_default=sa.text("'reps_weight'")),
        sa.Column("equipment", sa.Text),
        sa.Column("mechanics", sa.Text),
        sa.Column("weight_basis", sa.Text, nullable=False, server_default=sa.text("'total'")),
        sa.Column("primary_muscles", postgresql.ARRAY(sa.Text), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("secondary_muscles", postgresql.ARRAY(sa.Text), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("progression_scheme", sa.Text),
        sa.Column("video_url", sa.Text),
        sa.Column("notes", sa.Text),
        *TAIL,
        sa.CheckConstraint(f"tracking in {TRACKING}", name="exercise_tracking_check"),
        sa.CheckConstraint(f"weight_basis in {WEIGHT_BASIS}", name="exercise_weight_basis_check"),
    )
    op.create_index("exercise_primary_muscles_idx", "exercise", ["primary_muscles"], postgresql_using="gin")
    op.create_index("exercise_alive_idx", "exercise", ["name"], postgresql_where=sa.text("deleted_at is null"))

    # ----------------------------------------------------------------- routine
    op.create_table(
        "routine",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("notes", sa.Text),
        *TAIL,
    )

    # ------------------------------------------------------------ routine_item
    op.create_table(
        "routine_item",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("routine_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("routine.id", ondelete="CASCADE"), nullable=False),
        sa.Column("exercise_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("exercise.id"), nullable=False),
        sa.Column("position", sa.Integer, nullable=False),
        sa.Column("target_sets", sa.Integer),
        sa.Column("target_reps", sa.Integer),
        sa.Column("target_weight_kg", sa.Numeric(6, 2)),
        sa.Column("target_duration_s", sa.Integer),
        sa.Column("notes", sa.Text),
        *TAIL,
        sa.UniqueConstraint("routine_id", "position", name="routine_item_routine_position_key"),
    )
    op.create_index("routine_item_exercise_idx", "routine_item", ["exercise_id"])

    # ----------------------------------------------------------------- session
    op.create_table(
        "session",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("routine_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("routine.id")),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True)),
        sa.Column("notes", sa.Text),
        *TAIL,
    )
    op.create_index("session_started_idx", "session", [sa.text("started_at desc")])

    # ------------------------------------------------------------ session_item
    op.create_table(
        "session_item",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("session_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("session.id", ondelete="CASCADE"), nullable=False),
        sa.Column("exercise_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("exercise.id"), nullable=False),
        sa.Column("position", sa.Integer, nullable=False),
        sa.Column("notes", sa.Text),
        *TAIL,
        sa.UniqueConstraint("session_id", "position", name="session_item_session_position_key"),
    )
    op.create_index("session_item_session_idx", "session_item", ["session_id"])
    op.create_index("session_item_exercise_idx", "session_item", ["exercise_id"])

    # --------------------------------------------------------------- set_entry
    op.create_table(
        "set_entry",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("session_item_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("session_item.id", ondelete="CASCADE"), nullable=False),
        sa.Column("set_number", sa.Integer, nullable=False),
        sa.Column("status", sa.Text, nullable=False, server_default=sa.text("'done'")),
        sa.Column("reps", sa.Integer),
        sa.Column("weight_kg", sa.Numeric(6, 2)),
        sa.Column("duration_s", sa.Integer),
        sa.Column("distance_m", sa.Integer),
        sa.Column("rpe", sa.Numeric(3, 1)),
        sa.Column("notes", sa.Text),
        *TAIL,
        sa.UniqueConstraint("session_item_id", "set_number", name="set_entry_item_set_key"),
        sa.CheckConstraint(f"status in {SET_STATUS}", name="set_entry_status_check"),
        sa.CheckConstraint("reps is null or reps >= 0", name="set_entry_reps_check"),
        sa.CheckConstraint("weight_kg is null or weight_kg >= 0", name="set_entry_weight_check"),
        sa.CheckConstraint("duration_s is null or duration_s >= 0", name="set_entry_duration_check"),
        sa.CheckConstraint("rpe is null or (rpe >= 1 and rpe <= 10)", name="set_entry_rpe_check"),
    )
    op.create_index("set_entry_item_idx", "set_entry", ["session_item_id"])

    # -------------------------------------------------------------------- views
    # Derived values are views, never columns. See `Specs - Database schema`.
    op.execute(
        """
        create view v_set as
        select
          se.id            as set_id,
          se.set_number,
          se.status,
          se.reps,
          se.weight_kg,
          se.duration_s,
          se.distance_m,
          se.rpe,
          se.notes,
          se.extra,
          si.id            as session_item_id,
          si.exercise_id,
          e.name           as exercise_name,
          e.tracking,
          e.weight_basis,
          si.session_id,
          s.started_at,
          (s.started_at at time zone 'Pacific/Auckland')::date as session_date
        from set_entry se
        join session_item si on si.id = se.session_item_id
        join session      s  on s.id  = si.session_id
        join exercise     e  on e.id  = si.exercise_id
        where se.deleted_at is null
          and si.deleted_at is null
          and s.deleted_at  is null
          and e.deleted_at  is null
        """
    )
    op.execute(
        """
        create view v_e1rm as
        select
          *,
          round(weight_kg * (1 + reps / 30.0), 1) as e1rm_kg
        from v_set
        where tracking = 'reps_weight'
          and status   = 'done'
          and reps      is not null
          and reps      > 0
          and weight_kg is not null
          and weight_kg > 0
        """
    )
    op.execute(
        """
        create view v_session_volume as
        select
          session_id,
          session_date,
          sum(weight_kg * reps * case when weight_basis = 'per_hand' then 2 else 1 end)
            filter (where status = 'done')           as volume_kg,
          count(*) filter (where status = 'done')    as sets_done,
          count(*) filter (where status = 'missed')  as sets_missed
        from v_set
        group by session_id, session_date
        """
    )
    op.execute(
        """
        create view v_exercise_last as
        select distinct on (exercise_id)
          exercise_id,
          exercise_name,
          session_date       as last_date,
          reps, weight_kg, duration_s,
          set_number
        from v_set
        where status = 'done'
        order by exercise_id, started_at desc, set_number desc
        """
    )


def downgrade() -> None:
    for view in ("v_exercise_last", "v_session_volume", "v_e1rm", "v_set"):
        op.execute(f"drop view if exists {view}")
    for table in ("set_entry", "session_item", "session", "routine_item", "routine", "exercise"):
        op.drop_table(table)
