"""SQLAlchemy 2.0 models for the six Kratos tables.

These mirror `Specs - Database schema` one-to-one. The models exist so the API can
read and write rows; the schema of record is the Alembic migration, and the views
(`v_set`, `v_e1rm`, `v_session_volume`, `v_exercise_last`) are declared in
`app/views.py` because they are query-only.

Two conventions carry across every table, from the spec:

- the standard tail is `created_at`, `updated_at`, `deleted_at`, `extra`
- keys are UUIDs generated by the client, so an offline session already has its ID
  and the server write is an idempotent upsert
"""

import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base

TRACKING_VALUES = ("reps_weight", "reps_only", "duration", "completion", "distance_duration")
WEIGHT_BASIS_VALUES = ("total", "per_hand")
SET_STATUS_VALUES = ("done", "missed", "skipped")


def _uuid_pk() -> Mapped[uuid.UUID]:
    return mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)


class TimestampMixin:
    """The standard tail shared by every table."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    extra: Mapped[dict] = mapped_column(JSONB, nullable=False, server_default="{}")


class Exercise(TimestampMixin, Base):
    """The catalogue of things that can be performed."""

    __tablename__ = "exercise"

    id: Mapped[uuid.UUID] = _uuid_pk()
    name: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    tracking: Mapped[str] = mapped_column(Text, nullable=False, server_default="reps_weight")
    equipment: Mapped[str | None] = mapped_column(Text)
    mechanics: Mapped[str | None] = mapped_column(Text)
    weight_basis: Mapped[str] = mapped_column(Text, nullable=False, server_default="total")
    primary_muscles: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, server_default="{}"
    )
    secondary_muscles: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, server_default="{}"
    )
    progression_scheme: Mapped[str | None] = mapped_column(Text)
    video_url: Mapped[str | None] = mapped_column(Text)
    notes: Mapped[str | None] = mapped_column(Text)

    __table_args__ = (
        CheckConstraint(f"tracking in {TRACKING_VALUES}", name="exercise_tracking_check"),
        CheckConstraint(f"weight_basis in {WEIGHT_BASIS_VALUES}", name="exercise_weight_basis_check"),
        Index("exercise_primary_muscles_idx", "primary_muscles", postgresql_using="gin"),
    )


class Routine(TimestampMixin, Base):
    """A planned workout, reusable."""

    __tablename__ = "routine"

    id: Mapped[uuid.UUID] = _uuid_pk()
    name: Mapped[str] = mapped_column(Text, nullable=False)
    notes: Mapped[str | None] = mapped_column(Text)

    items: Mapped[list["RoutineItem"]] = relationship(
        back_populates="routine", cascade="all, delete-orphan", order_by="RoutineItem.position"
    )


class RoutineItem(TimestampMixin, Base):
    """One exercise slot inside a routine, with nullable targets."""

    __tablename__ = "routine_item"

    id: Mapped[uuid.UUID] = _uuid_pk()
    routine_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("routine.id", ondelete="CASCADE"), nullable=False
    )
    exercise_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("exercise.id"), nullable=False
    )
    position: Mapped[int] = mapped_column(Integer, nullable=False)
    target_sets: Mapped[int | None] = mapped_column(Integer)
    target_reps: Mapped[int | None] = mapped_column(Integer)
    target_weight_kg: Mapped[Decimal | None] = mapped_column(Numeric(6, 2))
    target_duration_s: Mapped[int | None] = mapped_column(Integer)
    notes: Mapped[str | None] = mapped_column(Text)

    routine: Mapped[Routine] = relationship(back_populates="items")
    exercise: Mapped[Exercise] = relationship()

    __table_args__ = (
        UniqueConstraint("routine_id", "position", name="routine_item_routine_position_key"),
        Index("routine_item_exercise_idx", "exercise_id"),
    )


class Session(TimestampMixin, Base):
    """One workout that actually happened. `routine_id` is nullable."""

    __tablename__ = "session"

    id: Mapped[uuid.UUID] = _uuid_pk()
    routine_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("routine.id")
    )
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    notes: Mapped[str | None] = mapped_column(Text)

    items: Mapped[list["SessionItem"]] = relationship(
        back_populates="session", cascade="all, delete-orphan", order_by="SessionItem.position"
    )

    __table_args__ = (Index("session_started_idx", started_at.desc()),)


class SessionItem(TimestampMixin, Base):
    """One exercise as performed within a session.

    Sets hang off this rather than the session, so the same exercise can appear
    twice (a warm-up plus a working block) and per-exercise data has a home.
    """

    __tablename__ = "session_item"

    id: Mapped[uuid.UUID] = _uuid_pk()
    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("session.id", ondelete="CASCADE"), nullable=False
    )
    exercise_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("exercise.id"), nullable=False
    )
    position: Mapped[int] = mapped_column(Integer, nullable=False)
    notes: Mapped[str | None] = mapped_column(Text)

    session: Mapped[Session] = relationship(back_populates="items")
    exercise: Mapped[Exercise] = relationship()
    sets: Mapped[list["SetEntry"]] = relationship(
        back_populates="session_item", cascade="all, delete-orphan", order_by="SetEntry.set_number"
    )

    __table_args__ = (
        UniqueConstraint("session_id", "position", name="session_item_session_position_key"),
        Index("session_item_session_idx", "session_id"),
        Index("session_item_exercise_idx", "exercise_id"),
    )


class SetEntry(TimestampMixin, Base):
    """One set. Every metric column is nullable, so one table covers all trackings."""

    __tablename__ = "set_entry"

    id: Mapped[uuid.UUID] = _uuid_pk()
    session_item_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("session_item.id", ondelete="CASCADE"), nullable=False
    )
    set_number: Mapped[int] = mapped_column(Integer, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="done")
    reps: Mapped[int | None] = mapped_column(Integer)
    weight_kg: Mapped[Decimal | None] = mapped_column(Numeric(6, 2))
    duration_s: Mapped[int | None] = mapped_column(Integer)
    distance_m: Mapped[int | None] = mapped_column(Integer)
    rpe: Mapped[Decimal | None] = mapped_column(Numeric(3, 1))
    notes: Mapped[str | None] = mapped_column(Text)

    session_item: Mapped[SessionItem] = relationship(back_populates="sets")

    __table_args__ = (
        UniqueConstraint("session_item_id", "set_number", name="set_entry_item_set_key"),
        CheckConstraint(f"status in {SET_STATUS_VALUES}", name="set_entry_status_check"),
        CheckConstraint("reps is null or reps >= 0", name="set_entry_reps_check"),
        CheckConstraint("weight_kg is null or weight_kg >= 0", name="set_entry_weight_check"),
        CheckConstraint("duration_s is null or duration_s >= 0", name="set_entry_duration_check"),
        CheckConstraint(
            "rpe is null or (rpe >= 1 and rpe <= 10)", name="set_entry_rpe_check"
        ),
        Index("set_entry_item_idx", "session_item_id"),
    )
